hw1 : source1.o 151044079_main.o 
	g++ -o exe 151044079_main.o source1.o

source1.o : source1.cpp
	g++ -c -std=c++11 source1.cpp

151044079_main.o : 151044079_main.cpp
	g++ -c -std=c++11 151044079_main.cpp

clean:
	rm *.o exe
	rm *.exe exe
